### ISSUE TITLE
RFC: Trigger Support

### ISSUE THREAD

**Issue by Hoverbear** [tcdi/pgx#503]
We'd like PGX (and, as a consequence, PL/Rust) to support triggers.

Part of that support is #502 . 

Triggers could be defined by

```rust
#[pg_trigger(
  before(insert, update),
  each(row),
)]
fn trigger_example(ctx: Trigger) -> pgx::Trigger {
  let old = &ctx.OLD;
  let new = &ctx.NEW;
  let relname = &ctx.TG_RELNAME;

  new
}
```

The syntax remains undecided for now, but we should ensure we could at least support the options available to `CREATE TRIGGER`: https://www.postgresql.org/docs/current/sql-createtrigger.html

**Comment by timClicks** [comment]
What is a `Trigger` context object? Is this something defined by `pgx`?

**Comment by eeeebbbbrrrr** [comment]
Looks pretty good!

**Comment by Hoverbear** [comment]
This is done in the `develop-v0.5.0` branch.

**Comment by johnrballard** [comment]
## Tasks

- [ ] #502 
- [x] #558
- [ ] #604
- [ ] An immutable “OLD” HeapTuple instance,
- [ ] A mutable “NEW” HeapTuple instance,
- [ ] Access to trigger constant string arguments,
- [ ] Access to all PostgreSQL state variables as outlined here: https://www.postgresql.org/docs/current/plpgsql-trigger.html
- [ ] Ability to return “NULL”, “OLD”, or “NEW”
